In [1]:
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

In [2]:

grid = np.random.randint(1, 3, size=(6, 7))

def reachquick(grid, m, n):
    '''
    grid : a 2d numpy array or a list of the lists
    m : target column
    n: target row
    '''
    # Assiging 0 to all og the cells in the given grid
    reachquick = [[0 for x in range(n+1)] for y in range(m+1)]    
    
    # The first cell, the time spent on the first cell is the time stated! 
    # So we assign the minutes at the first cell to the starting position 
    # of the grid
    reachquick[0][0] = grid[0][0]
    
    # Lets calculate the total time to reach the bottom of the first column, 
    # cummalatively.
    for i in range (1, m+1):
        upper_cell = reachquick[i - 1][0]
        reachquick[i][0] = upper_cell + grid[i][0]   
    
    # Same as above for the first row
    for j in range (1, n+1):
        left_cell = reachquick[0][j - 1]
        reachquick[0][j] = left_cell + grid[0][j]
        
    # Running another loop for all the remaining cells.
    # As this being done for the cells other than the first row and 
    # the first column, each cell in this loops pairs up with either
    # the cell on the top, or the cell on the left, and chosing the 
    # path with lowest sum of minutes
    for i in range (1, m+1):
        for j in range (1, n+1):
            left_cell =  reachquick[i - 1][j]
            upper_cell = reachquick[i][j - 1]
            reachquick[i][j] = grid[i][j] + min(left_cell,upper_cell)
    print(grid)
    
    quickest_path =  reachquick[m][n]
    return quickest_path



shortest_time = reachquick(grid, 5,6)
print('Shortest minutes possible : ',shortest_time)





[[1 1 2 1 1 1 2]
 [1 2 1 2 1 1 2]
 [1 1 2 1 2 2 1]
 [2 2 2 2 1 1 2]
 [1 1 1 1 2 1 1]
 [1 1 1 1 1 1 2]]
Shortest minutes possible :  14
